### ISSUE TITLE
Would this potentially trigger the "pattern day trader" in RH?

### ISSUE THREAD

**Issue by emaxsaun** [Jake0303/RobinHood-RSI-Trading-Bot#11]
Would this potentially trigger the "pattern day trader" in RH?

**Comment by breitbarth** [comment]
Not if you limit it to under 5 trades per stock
________________________________

**Comment by emaxsaun** [comment]
@breitbarth Thanks for the quick reply. What line controls that? Is that the rsiPeriod?

**Comment by Jake0303** [comment]
Hi @emaxsaun yes it would, you would want to code some PDT counter that would increase by 1 for each sell then reset the PDT counter to 0 every day on market open.

**Comment by emaxsaun** [comment]
Thanks @Jake0303!
